# Generated by Django 5.0.6 on 2024-08-12 16:34

import tenant_schemas.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="schema_name",
            field=models.CharField(
                max_length=63,
                unique=True,
                validators=[tenant_schemas.postgresql_backend.base._check_schema_name],
            ),
        ),
    ]
