# Generated by Django 5.0.6 on 2024-07-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_alter_actionremark_tenant_alter_anomaly_tenant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionremark",
            name="date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="anomaly",
            name="detection_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="layout",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="end_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="results",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="start_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="confidence_interval",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="forecast_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldata",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="metric",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="metric",
            name="type",
            field=models.CharField(
                choices=[
                    ("KPI", "Key Performance Indicator"),
                    ("North Star", "North Star Metric"),
                    ("Input Metric", "Input Metric"),
                    ("Diagnosis", "Diagnosis Metric"),
                    ("Output Metric", "Output Metric"),
                ],
                db_index=True,
                default="KPI",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("Count", "Count"),
                    ("Percentage", "Percentage"),
                    ("Currency", "Currency"),
                    ("Ratio", "Ratio"),
                ],
                default="Count",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="report",
            name="configuration",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="report",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="target",
            name="target_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="trend",
            name="end_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="trend",
            name="start_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="actionremark",
            index=models.Index(
                fields=["metric", "date"], name="metrics_act_metric__be3429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["metric", "detection_date"],
                name="metrics_ano_metric__84982d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["from_metric", "to_metric"],
                name="metrics_con_from_me_9411ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(
                fields=["start_date", "end_date"], name="metrics_exp_start_d_04716a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["metric", "forecast_date"],
                name="metrics_for_metric__4c9ae2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historicaldata",
            index=models.Index(
                fields=["metric", "date"], name="metrics_his_metric__a2923a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metric",
            index=models.Index(
                fields=["name", "type"], name="metrics_met_name_c9d100_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metric",
            index=models.Index(
                fields=["last_updated"], name="metrics_met_last_up_7984a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["name", "project"], name="metrics_tag_name_1bdb27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(
                fields=["metric", "target_date"], name="metrics_tar_metric__234682_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trend",
            index=models.Index(
                fields=["metric", "start_date", "end_date"],
                name="metrics_tre_metric__d386bb_idx",
            ),
        ),
    ]
