# Generated by Django 5.0.6 on 2024-07-22 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics",
            "0003_alter_actionremark_date_alter_anomaly_detection_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="connection",
            name="metrics_con_from_me_9411ea_idx",
        ),
        migrations.AddField(
            model_name="connection",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="metrics.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("tenant", "from_metric", "to_metric")},
        ),
    ]
