# Generated by Django 5.0.6 on 2024-07-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0004_remove_connection_metrics_con_from_me_9411ea_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="project",
        ),
        migrations.AddField(
            model_name="metric",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="metrics.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="metric",
            unique_together={("tenant", "project", "name")},
        ),
    ]
