# Generated by Django 5.0.6 on 2024-07-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0007_connection_strength_forecast_lower_bound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataqualityscore",
            name="metric",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_quality_scores",
                to="metrics.metric",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataqualityscore",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_quality_scores",
                to="metrics.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicaldata",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="dataqualityscore",
            unique_together={("tenant", "metric", "project")},
        ),
    ]
