# Generated by Django 5.0.6 on 2024-07-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0008_dataqualityscore_metric_dataqualityscore_project_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metric",
            unique_together={("tenant", "project", "name")},
        ),
    ]
