# Generated by Django 5.0.6 on 2024-08-02 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0010_movingaverage_tenant_networkanalysisresult_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="metric",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="metrics.metric",
            ),
            preserve_default=False,
        ),
    ]
