# Generated by Django 5.0.6 on 2024-08-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0012_report_analysis_result_report_anomaly_result_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trendchangepoint",
            name="tenant",
        ),
        migrations.AlterField(
            model_name="trendchangepoint",
            name="significance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
