# Generated by Django 5.0.6 on 2024-08-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0013_remove_trendchangepoint_tenant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trendchangepoint",
            old_name="change_type",
            new_name="direction",
        ),
    ]
