# Generated by Django 5.0.6 on 2024-08-05 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0014_rename_change_type_trendchangepoint_direction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seasonalityresult",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AddField(
            model_name="seasonalityresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
