# Generated by Django 5.0.6 on 2024-08-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0015_alter_seasonalityresult_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seasonalityresult",
            unique_together={("metric", "seasonality_type")},
        ),
        migrations.RemoveField(
            model_name="seasonalityresult",
            name="tenant",
        ),
    ]
