# Generated by Django 5.0.6 on 2024-08-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0017_computationstatus_notification_pendingcomputation"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonalityresult",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_%(class)ss",
                to="metrics.client",
            ),
            preserve_default=False,
        ),
    ]
